exports.getBalance = require("./simple-coin/get-balance")
exports.getAddress = require("./get-address")
exports.cidToBytes = require("./cid-to-bytes")
exports.makeDealProposal = require("./deal-client/make-deal-proposal")
exports.getDealProposal = require("./deal-client/get-deal-proposal")